# Generated by Django 2.1.5 on 2019-08-21 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('last_update', models.DateTimeField(default=datetime.datetime(2019, 8, 21, 10, 59, 24, 575967))),
            ],
        ),
    ]
